### ISSUE TITLE
Search Results show NO IMAGE on random occasions

### ISSUE THREAD

**Issue by SvenTUM** [mrmap-community/GeoPortal.rlp#15]
### Describe the bug ###

When searching for _WMS_  or _WMC_ the search results are missing some of the extent images.

### To Reproduce ###

1. Go to a GeoPortal e.g. [GeoPortal.rlp](https://www.geoportal.rlp.de/)
2. Start a search
3. Open some WMS or WMC searches
4. See _NO IMAGE_ graphic in place of the extent image.

### Expected behavior ###

The extent should be shown with the configured base map in the background.

### Screenshots ###

![Screenshot 2021-10-22 133013](https://user-images.githubusercontent.com/8211898/138447712-4e8811d8-0e1a-467d-ac5d-8cd047cb6a58.jpg)

**Comment by holsandre** [comment]
its not random, if you look closely you'll see it always happens on all sublayers after the first one and its because the function which generates these extent images is faulty, its this one:

https://github.com/mrmap-community/GeoPortal.rlp/blob/master/searchCatalogue/utils/viewHelper.py#L462-L482

i made a non recursive function of this, i dont think recursion is needed here because we always know the length of the list(number of sublayers), not sure why this one is recursive 

i already pushed it to this branch, going to merge it tomorrow it think.
https://github.com/mrmap-community/GeoPortal.rlp/tree/15_no_extent_images

**Comment by holsandre** [comment]
fixed in https://github.com/mrmap-community/GeoPortal.rlp/pull/16
